class Contact {
  final String name;
  final String status;
  final String group;
  final String email;
  final String location;
  final String phone;
  final String birthday;
  final String position;

  Contact({
    required this.name,
    required this.status,
    required this.group,
    required this.email,
    required this.location,
    required this.phone,
    required this.birthday,
    required this.position,
  });
}

final List<Contact> contacts = [
  Contact(
    name: 'Kashi Levin',
    status: 'Active',
    group: 'SILUUK Group',
    email: 'krutchevinfo@sample.com',
    location: 'Manchester, USA',
    phone: '(201) 555-0124',
    birthday: 'July 24, 1988',
    position: '',
  ),
  Contact(
    name: 'Efruk Nagop',
    status: 'Active',
    group: '',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Software Developer',
  ),
  Contact(
    name: 'Covey Schiefer',
    status: 'INSGENE',
    group: 'INSGENE',
    email: 'coveekon@test.com',
    location: 'Montreal, Canada',
    phone: '(804) 335-2403',
    birthday: 'Jan 4, 1989',
    position: 'Software Developer',
  ),
  Contact(
    name: 'Centre Bergson',
    status: 'Active',
    group: '',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Hit Manager',
  ),
  Contact(
    name: 'Jaylee Amtseff',
    status: 'Active',
    group: '',
    email: 'jaylewant22@test.com',
    location: 'Chicago, USA',
    phone: '(217) 555-0113',
    birthday: 'Oct 22, 1990',
    position: 'Hit Manager',
  ),
  Contact(
    name: 'Justin Korgauer',
    status: 'Active',
    group: '',
    email: 'justtimez87@sample.com',
    location: 'Calgary, Canada',
    phone: '(833) 752-5811',
    birthday: 'Mar 11, 1988',
    position: 'Accountant',
  ),
  Contact(
    name: 'Mark Dias',
    status: 'INSGENE',
    group: 'SILUUK Group',
    email: 'markdidasj@example.com',
    location: 'Los Angeles, USA',
    phone: '(408) 555-0103',
    birthday: 'May 23, 1992',
    position: '',
  ),
  Contact(
    name: 'John Aminoff',
    status: 'Active',
    group: '',
    email: 'amhoff@kate@test.com',
    location: 'San Francisco, USA',
    phone: '(260) 555-0104',
    birthday: 'Dec 28, 1991',
    position: 'Software Developer',
  ),
  Contact(
    name: 'Allison Schiefer',
    status: 'Active',
    group: '',
    email: 'allisonschiefer@sample.com',
    location: 'Houston, USA',
    phone: '(884) 555-0102',
    birthday: 'Apr 6, 1985',
    position: 'Accountant',
  ),
  Contact(
    name: 'Cooper Calda',
    status: 'Active',
    group: '',
    email: 'capgregotni@akmo.com',
    location: 'Miami, USA',
    phone: '(808) 555-0111',
    birthday: 'Feb 25, 1989',
    position: 'Software Developer',
  ),
  Contact(
    name: 'Guadino Koregguer',
    status: 'Active',
    group: '',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Support',
  ),
  Contact(
    name: 'Merets Lipshitz',
    status: 'Active',
    group: '',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Accountant',
  ),
  Contact(
    name: 'Martin Vernon',
    status: 'Active',
    group: '',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Software Developer',
  ),
  Contact(
    name: 'Lydia Mango',
    status: 'Active',
    group: '',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Software Developer',
  ),
  Contact(
    name: 'Charlie Schiefer',
    status: 'INSGENE',
    group: 'INSGENE',
    email: '',
    location: '',
    phone: '',
    birthday: '',
    position: 'Support',
  ),
];